export const BUSINESS_TYPES = [
  'Restaurant',
  'Cafe',
  'Salon',
  'Spa',
  'Dental Clinic',
  'Medical Clinic',
  'Gym',
  'Moving Company',
  'Cleaning Company',
  'HVAC Company',
  'Electrical Company',
  'Landscaping Company',
  'Real Estate',
  'Photography',
  'Other',
] as const

export const STORAGE_BUCKETS = {
  LOGOS: 'logos',
  COVERS: 'covers',
  ITEMS: 'items',
  GALLERY: 'gallery',
} as const

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  DASHBOARD: '/dashboard',
  SETUP: '/dashboard/setup',
  CATALOGUE: '/dashboard/catalogue',
  CATEGORIES: '/dashboard/categories',
  BUSINESS_INFO: '/dashboard/business-info',
  ABOUT: '/dashboard/about',
  TESTIMONIALS: '/dashboard/testimonials',
  GALLERY: '/dashboard/gallery',
  CONTACT: '/dashboard/contact',
  WORKING_HOURS: '/dashboard/working-hours',
  BOOKINGS: '/dashboard/bookings',
  REVIEWS: '/dashboard/reviews',
  MESSAGES: '/dashboard/messages',
  ANALYTICS: '/dashboard/analytics',
  MARKETING: '/dashboard/marketing',
  QR: '/dashboard/qr',
  THEMES: '/dashboard/themes',
  ACCOUNT: '/dashboard/account',
} as const
